[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["Ram Kumar R"]

# The title and description fields are primarily for displaying extension info in UI
title = "Python Runner"
description="Run project Python scripts from the Run menu."

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Tools"

# Keywords for the extension
keywords = ["kit", "scripts", "runner"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.menu.utils" = {}

# Main python module this extension provides, it will be publicly available as "import omniverse_learning.tools".
[[python.module]]
name = "omniverse_learning.tools"

